[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"

[tool.autopep8]
max_line_length = 100

[tool.pylint.messages_control]
disable = [
  "redefined-builtin",
  "singleton-comparison"
]